//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalleWebData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFrame
    {
        public int CN_FramePK { get; set; }
        public int CN_FrameSpilPK { get; set; }
        public int CN_FrameNr { get; set; }
        public int CN_FrameScore { get; set; }
    
        public virtual tblSpil tblSpil { get; set; }
    }
}
